# Generated by Django 5.1.6 on 2025-04-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packinglist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_ai_suggested",
            field=models.BooleanField(default=False),
        ),
    ]
