# Generated by Django 5.1.6 on 2025-04-18 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packinglist", "0002_item_is_ai_suggested"),
        ("trips", "0010_inputtrip_activities_list_inputtrip_considerations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="trips.inputtrip",
            ),
        ),
    ]
