# Generated by Django 5.1.6 on 2025-04-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inputtrip",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
            },
        ),
    ]
