# Generated by Django 5.1.6 on 2025-04-14 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_inputtrip_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputtrip",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 14, 18, 4, 14, 454512, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
