# Generated by Django 5.1.5 on 2025-04-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_inputtrip_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelRecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='travel_recs')),
            ],
        ),
    ]
