# Generated by Django 5.1.5 on 2025-04-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_travelrecs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='travelRecs',
            new_name='travelRecommendations',
        ),
    ]
