# Generated by Django 5.1.5 on 2025-04-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_rename_travelrecs_travelrecommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrecommendations',
            name='image',
            field=models.ImageField(upload_to='travel_recs/'),
        ),
    ]
