# Generated by Django 5.2 on 2025-04-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0009_alter_travelrecommendations_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputtrip",
            name="activities_list",
            field=models.TextField(
                blank=True, null=True, verbose_name="Activities List"
            ),
        ),
        migrations.AddField(
            model_name="inputtrip",
            name="considerations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional Considerations"
            ),
        ),
        migrations.AddField(
            model_name="inputtrip",
            name="packing_list",
            field=models.TextField(blank=True, null=True, verbose_name="Packing List"),
        ),
        migrations.AddField(
            model_name="inputtrip",
            name="weather",
            field=models.TextField(blank=True, null=True, verbose_name="Weather Info"),
        ),
    ]
