# Generated by Django 5.2 on 2025-04-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0010_inputtrip_activities_list_inputtrip_considerations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inputtrip",
            name="activities",
        ),
    ]
