# Generated by Django 5.1.6 on 2025-04-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0012_remove_inputtrip_activities_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputtrip",
            name="activities_list",
            field=models.TextField(
                blank=True, null=True, verbose_name="Activities List"
            ),
        ),
    ]
