# Generated by Django 5.1.4 on 2025-04-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_inputtrip_activities_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtrip',
            name='notified',
            field=models.BooleanField(null=True, verbose_name='User has been notified'),
        ),
    ]
