# Generated by Django 5.1.5 on 2025-04-25 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_inputtrip_activities_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtrip',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
