# Generated by Django 5.1.5 on 2025-04-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_tripinvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripinvite',
            old_name='invited_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='tripinvite',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='tripinvite',
            name='invited_user',
        ),
        migrations.AlterField(
            model_name='tripinvite',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.inputtrip'),
        ),
    ]
