# Generated by Django 5.1.4 on 2025-04-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_inputtrip_notified'),
        ('trips', '0016_rename_invited_email_tripinvite_email_and_more'),
    ]

    operations = [
    ]
