# Generated by Django 5.1.4 on 2025-04-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_merge_20250426_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtrip',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='User has been notified'),
        ),
    ]
